
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-demo


#blue green
---
kind: Service
apiVersion: v1
metadata:
  namespace: argo-demo
  name: rollout-ngnix-active # <- active 
spec:
  selector:
    app.kubernetes.io/name: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
kind: Service
apiVersion: v1
metadata:
  namespace: argo-demo
  name: rollout-ngnix-preview # <- preview
spec:
  selector:
    app.kubernetes.io/name: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx
  namespace: argo-demo
spec:
  replicas: 2
  strategy:
    blueGreen:
      previewService: rollout-ngnix-preview # <- matches Preview Service metadata
      activeService: rollout-ngnix-active # <- matches Active Service metadata 
      previewReplicaCount: 2
      autoPromotionEnabled: false
      # autoPromotionSeconds: 1
      scaleDownDelaySeconds: 30
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:perl
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m



