name: Destroy Eph.Env

on: #workflow_dispatch
  pull_request:
    types:
      - closed

jobs:
  Destroy-SQS-Lambda-VCluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code Repository
        uses: actions/checkout@v3 #####v2

      - name: Set up SSH agent for Clone TF Remote Repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRI }}

      - name: Clone & Copy TF-Modules from Remote Repository #
        run: |
            TF_REMOTE_REPO="${{ secrets.TF_REMOTE_REPO }}"
            git clone --depth=1 git@github.com:${{ github.repository_owner }}/${TF_REMOTE_REPO}.git temp_repo
            mv temp_repo/modules . && rm -rf temp_repo

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TEST1_V }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TEST1_V }}
          aws-region: us-east-1
          KUBECONFIG: ~/.kube/config
         
      - name: Disconnect Lambda-Existing VPC
        run: aws lambda update-function-configuration --function-name eepr${{ github.event.number }}-gl-stg-lambda --vpc-config SubnetIds=[],SecurityGroupIds=[]
      
      - name: Replace PR-No inside TFVars & S3-TF-StateFile
        run: |
          sed -i "s/GHPRNO/${{ github.event.number }}/g" tf-config/main.tf         #include GH-PR-No in S3 TFState Name 
          sed -i "s/GHPRNO/${{ github.event.number }}/g" tf-config/stg.tfvars      #include GH-PR-No in components Name

      - name: Terraform Init to Destroy Resources
        id: tf-destroy
        working-directory: ./tf-config
        run: |
          terraform init
          terraform destroy -var-file stg.tfvars -auto-approve -input=false

      - name: Delete plan file
        if: steps.tf-destroy.outcome == 'success'
        run: aws s3 rm s3://eph-env-test-s3/eepr${{ github.event.number }}-tfstate

      - name: Generate kube config
        run: aws eks update-kubeconfig --region us-east-1 --name ${{ secrets.EKS_TEST_CLUSTER_NAME }}

      - name: Set up PostgreSQL Client
        run: sudo apt-get install -y postgresql-client

      - name: Set up Bastion-Host SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
            ssh-private-key: ${{ secrets.BASTION_PRIVATE_KEY }}

      - name: Bastion-Host SSH & Drop New RDS-Schema 
        run: |
          ssh -o StrictHostKeyChecking=no -A -L 5432:34.207.98.242:5432 ec2-user@34.207.98.242 'bash -s' << 'EOF'
            export PGPASSFILE=~/gl-notifications-test-rds.pgpass
            sudo chmod 600 gl-notifications-test-rds.pgpass
            sudo chown ec2-user:ec2-user ~/gl-notifications-test-rds.pgpass
            psql -h gl-notifications-test-rds.cluster-c74weq8kegwi.us-east-1.rds.amazonaws.com -p 5432 -U retailtest -d gl-notifications-test-rds -c "DROP SCHEMA IF EXISTS eepr${{ github.event.number }};"
          EOF
         
      - name: install vcluster plugin to delete VCluster PR 
        run: |
          curl -L -o vcluster "https://github.com/loft-sh/vcluster/releases/latest/download/vcluster-linux-amd64" && sudo install -c -m 0755 vcluster /usr/local/bin && sudo rm -f vcluster
          vcluster delete eepr${{ github.event.number }} --auto-delete-namespace
          
         